---
# tasks file for vim-setting
- name: vim setting
  become_user: ec2-user
  shell: |
    cat > ~/.vimrc <<EOL
    set number " line 표시를 해준다.
    set ai " auto indent
    set si " smart indent
    set shiftwidth=2 " shift를 2칸으로
    set ts=2 " tab을 2칸으로
    set hlsearch " 검색 시 하이라이트로 색상 강조
    set bs=indent,eol,start " backspace 키 사용
    set history=1000 " 명령어에 대한 히스토리를 1000개까지 저장
    set ruler " 상태표시줄에 커서의 위치 표시
    set showmatch " 매칭되는 괄호를 보여줌
    set nocompatible " 방향키로 이동 가능
    set expandtab " tab 을 space 로 변경.
    EOL


