---
- hosts: _bastion_ec2
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/dyheo-histech.pem"
  roles:
    - name: epel 
      tags:
        - epel

    - name: preconfig
      tags:
        - preconfig

    - name: vim-setting
      become_user: ec2-user
      become: true
      tags:
        - vim-setting

    - name: oh-my-zsh
      become_user: ec2-user
      become: true
      tags:
        - oh-my-zsh

    - name: zsh-setting
      become_user: ec2-user
      become: true
      tags:
        - zsh-setting

    - name: pem-copy
      become_user: ec2-user
      become: true
      tags:
        - pem-copy

